default: &default
  # some_salt: <%= ENV['SOME_SALT'] %>
  secret_key_base:  does_not_matter

development:
  <<: *default
  # secret_key_base:  development_secret_key_base

test:
  <<: *default
  # secret_key_base: test_secret_key_base

production:
  <<: *default
  # secret_key_base: <%= ENV['MARKETPLACE_SECRET_KEY_BASE'] %>
